### ISSUE TITLE
dump.cs encrypted?  // RVA: 0x13e4554 VA: 0x7eeddd9554 // Int64 FDEKPHJHCPF, String DNFEOCCGAEH etc.

### ISSUE THREAD

**Issue by AWO52PZ44IKE7FDR79DV2999BCZK19R0IFLDGHF** [Perfare/Riru-Il2CppDumper#10]
![Capture](https://user-images.githubusercontent.com/46418980/89891676-1bbce700-db9b-11ea-9015-e39e9c31bdfe.PNG)

![Capture](https://user-images.githubusercontent.com/46418980/89891250-55412280-db9a-11ea-995a-80bd751e83f3.PNG)

Not sure if I am doing something incorrectly or if I came across a bug. Either way, any idea how to read this file? 

Application is **ToonBlast** 

Uploaded my dump.cs file if you need to look at it: 
[<--- dump.cs --->](https://github.com/Perfare/Riru-Il2CppDumper/files/5056659/dump.zip)

Uninstalled/Reinstalled module, re-ran app. Same issue. 

Thank you for all the hard work! Please let me know how to donate.

**Comment by Perfare** [comment]
I don’t know what your problem is. I didn’t see any problem from your screenshot. The first picture should be caused by the game using obfuscation tools.
