### ISSUE TITLE
Unity version support 

### ISSUE THREAD

**Issue by ConsoleGaming** [Perfare/Riru-Il2CppDumper#14]

**Comment by ConsoleGaming** [comment]
Doesn`t work with unity version 2018.4.10f1

**Comment by Perfare** [comment]
https://github.com/Perfare/Riru-Il2CppDumper/blob/34f01a1f3566c0e2998fc3c860b7d0ec43486dda/module/src/main/cpp/game.h#L34
and
https://github.com/Perfare/Riru-Il2CppDumper/blob/34f01a1f3566c0e2998fc3c860b7d0ec43486dda/module/src/main/cpp/game.h#L11-L12
In addition, if you do not provide the game name and log, I will not be able to solve any problems

**Comment by ConsoleGaming** [comment]
the game name is pixelgun 3d and it just loads forever after implementing this module

**Comment by Perfare** [comment]
If your game is `com.pixel.gun3d`, I just tested it without any problems. If you still think there is a problem, you need to upload the log to me.

**Comment by ConsoleGaming** [comment]
should i give you magisk logs ?

**Comment by ConsoleGaming** [comment]
where can i find these logs in android

**Comment by ConsoleGaming** [comment]
I tried with other games too here is are the logs

**Comment by ConsoleGaming** [comment]
java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 2018.4.4f1
Device model      : Xiaomi Redmi Note 7
Device fingerprint: xiaomi/lavender/lavender:9/PKQ1.180904.001/V11.0.6.0.PFGMIXM:user/release-keys

Caused by: java.lang.Error: signal 6 (SIGABRT), code -6 (?), fault addr --------
Build fingerprint: 'xiaomi/lavender/lavender:9/PKQ1.180904.001/V11.0.6.0.PFGMIXM:user/release-keys'
Revision: '0'
pid: 9551, tid: 9564, name: m.habby.archer  >>> com.habby.archero <<<
    x0   0000000000000000  x1   000000000000255c  x2   0000000000000006  x3   0000000000000008
    x4   0000000000000000  x5   0000000000000000  x6   0000000000000000  x7   0000000000000000
    x8   0000000000000083  x9   71c34486efdc0e4d  x10  0000000000000000  x11  fffffffc7ffffbdf
    x12  0000000000000001  x13  ffffffffffffffff  x14  0000000000000000  x15  ffffffffffffffff
    x16  0000007f564a52b0  x17  0000007f563c4cd0  x18  0000000000000010  x19  000000000000254f
    x20  000000000000255c  x21  0000007eb218a000  x22  0000007ecce95de0  x23  0000007eb23a1000
    x24  0000007ebbb50570  x25  0000007ebba53000  x26  0000007f5bb905e0  x27  0000000000000000
    x28  0000007ed5c31460  x29  0000007ebbb4fe30  x30  0000007f563b8144
    sp   0000007ebbb4fdf0  pc   0000007f563b816c  pstate 0000000060000000

	at [vdso].(:0)
	at libc.abort(abort:112)
	at libil2cpp._ZN9__gnu_cxx27__verbose_terminate_handlerEv(_ZN9__gnu_cxx27__verbose_terminate_handlerEv:396)
	at libil2cpp._ZN10__cxxabiv111__terminateEPFvvE(_ZN10__cxxabiv111__terminateEPFvvE:8)
	at libil2cpp._ZSt9terminatev(_ZSt9terminatev:12)
	at libil2cpp.__cxa_throw(__cxa_throw:136)
	at libil2cpp.(:0)
	at libil2cpp.(:0)
	at libriru_il2cppdumper._Z11il2cpp_dumpPvPc(_Z11il2cpp_dumpPvPc:1260)
	at libriru_il2cppdumper._Z11hack_threadPv(_Z11hack_threadPv:536)
	at libc._ZL15__pthread_startPv(_ZL15__pthread_startPv:36)
	at libc.__start_thread(__start_thread:68)

**Comment by Perfare** [comment]
Same as #11 , you need to update the latest code.

**Comment by ConsoleGaming** [comment]
I tried the newest version from il2cpp(riru) but still same problem

**Comment by Perfare** [comment]
Could not reproduce the error, sorry I will not be able to fix it.
