### ISSUE TITLE
dump龙之谷2闪退

### ISSUE THREAD

**Issue by dc7777777** [Perfare/Riru-Il2CppDumper#16]
08-31 17:04:58.096 16072 16087 E CRASH   : signal 11 (SIGSEGV), code 0 (?), fault addr 000027f400003ec8
08-31 17:04:58.096 16072 16087 E CRASH   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-31 17:04:58.096 16072 16087 E CRASH   : Build fingerprint: 'xiaomi/lavender/lavender:10/QKQ1.190910.002/V12.0.1.0.QFGCNXM:user/release-keys'
08-31 17:04:58.096 16072 16087 E CRASH   : Revision: '0'
08-31 17:04:58.096 16072 16087 E CRASH   : pid: 16072, tid: 16087, name: com.tencent.wo  >>> com.tencent.wod <<<
08-31 17:04:58.096 16072 16087 E CRASH   :     x0   0000000000000000  x1   000000000000000b  x2   abc783bbf29a6ff5  x3   abc783bbf29a6ff5
08-31 17:04:58.096 16072 16087 E CRASH   :     x4   0000000000000006  x5   0000000000000000  x6   0000000000000000  x7   00000000000151cc
08-31 17:04:58.096 16072 16087 E CRASH   :     x8   0000000000000081  x9   abc783bbf29a6ff5  x10  0000000000000058  x11  0000000000000500
08-31 17:04:58.096 16072 16087 E CRASH   :     x12  0000000000069068  x13  00000003e8000000  x14  000501bc4963f400  x15  000094699229b782
08-31 17:04:58.096 16072 16087 E CRASH   :     x16  0000007b5ce7ddd0  x17  0000007bf291d9c0  x18  0000007b0ea80000  x19  0000000000003ed7
08-31 17:04:58.096 16072 16087 E CRASH   :     x20  0000007b5ce638d0  x21  0000000000000000  x22  000000000000000b  x23  0000000000000072
08-31 17:04:58.096 16072 16087 E CRASH   :     x24  0000007aab9a5400  x25  0000000000000000  x26  0000007b5ce638d0  x27  0000007b6d933e20
08-31 17:04:58.096 16072 16087 E CRASH   :     x28  0000007b5ce7f160  x29  0000007b6d933d90  x30  0000007b5ce4b8d0
08-31 17:04:58.096 16072 16087 E CRASH   :     sp   0000007b6d933c20  pc   0000007bf291d9c8  pstate 0000000060000000
08-31 17:04:58.096 16072 16087 E CRASH   : 
08-31 17:04:58.096 16072 16087 E CRASH   : backtrace:
08-31 17:04:58.097 16072 16087 E CRASH   : 	#00  pc 000000000033d33c  /data/app/com.tencent.wod-Y_NFBCkXQAS-DJMbEvF5_w==/lib/arm64/libunity.so
08-31 17:04:58.097 16072 16087 E CRASH   : 	#01  pc 0000000000361da4  /data/app/com.tencent.wod-Y_NFBCkXQAS-DJMbEvF5_w==/lib/arm64/libunity.so
08-31 17:04:58.097 16072 16087 E CRASH   : 	#02  pc 0000000000004dd8  /system/bin/app_process64
08-31 17:04:58.097 16072 16087 E CRASH   : 	#03  pc 0000000000000690  [vdso] (__kernel_rt_sigreturn)
08-31 17:04:58.097 16072 16087 E CRASH   : 	#04  pc 00000000000d19c8  /apex/com.android.runtime/lib64/bionic/libc.so (kill+8)
08-31 17:04:58.097 16072 16087 E CRASH   : 	#05  pc 00000000000078d0  /data/app/com.tencent.wod-Y_NFBCkXQAS-DJMbEvF5_w==/lib/arm64/libBugly.so
08-31 17:04:58.097 16072 16087 E CRASH   : 	#06  pc 0000000000004dd8  /system/bin/app_process64
08-31 17:04:58.097 16072 16087 E CRASH   : 	#07  pc 0000000000000690  [vdso] (__kernel_rt_sigreturn)

红米note8

**Comment by Perfare** [comment]
游戏修改了Unity引擎，隐藏了libil2cpp.so的导出函数，通过其新增的__dynamic_pointer导出函数获取il2cpp的api，函数位于libunity.so 0x87A3B0。需要特殊处理，基本没有难度，但是不考虑在Riru-Il2CppDumper添加。

**Comment by mxjspowsg** [comment]
dump原神闪退

**Comment by mxjspowsg** [comment]
@Perfare dump原神时闪退
