### ISSUE TITLE
miHoYo costume meta

### ISSUE THREAD

**Issue by sterling0x1** [Perfare/Riru-Il2CppDumper#19]
this developer uses costume metadata on their games and encrypts them. RiRu dumper fails to dump after getting il2cpp handle and/or base. Game just freezes or crash.

Any chance you could look into that?

com.miHoYo.bh3global
com.miHoYo.GenshinImpact

**Comment by Perfare** [comment]
Riru-Il2CppDumper does not depend on metadata, these games have been tested and can dump normally.

**Comment by AndnixSH** [comment]
True, it worked fine on both games for me too
Magisk 20.4, Android 9

**Comment by sterling0x1** [comment]
yeah thats right, it was an error on my end.
