### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by AndnixSH** [Perfare/Riru-Il2CppDumper#20]
I tried to make simple config file that reads out package name to myself but it seems it does not read the file. I'm not sure why. i have little knowledge in c++ and magisk module

Maybe you can try implement it?

**Comment by aylz10** [comment]
Make a configuration file for the GamePackageName variable in hook.cpp

**Comment by Perfare** [comment]
The configuration file now controls the code at compile time and cannot be made into an external file.

**Comment by AndnixSH** [comment]
That's unfortunately sad, i don't want to reinstall and reboot everytime. I'm still looking another way

**Comment by AndnixSH** [comment]
Auto-Il2cppdumper is much easier for me, and can be used on emulator https://platinmods.com/threads/how-to-use-auto-il2cppdumper-to-dump-protected-games-no-root.134194/
