### ISSUE TITLE
Does this dumper needs compatibility requirements based on android phone model and OS?

### ISSUE THREAD

**Issue by abegailabesamis06** [Perfare/Riru-Il2CppDumper#22]
I tried to use the samsung galaxy j7 core octa but fail to run the game running riru core and dumper in games . when activated and open the target game it force close the game automatically. i follow the instructions and put the right unity version . Any suggestions and advisable android device. My phone is rooted also and installed magisk. I can send a video proof about the error and android studio compile of the game if needed.

**Comment by 1354961639** [comment]
hello，I tried to compile this project with android studio but an error was reported. Can you provide me with a modified and compiled video?

**Comment by jokerart06** [comment]
close this issue. i resolve it now

**Comment by Perfare** [comment]
The program should work normally on most devices, but I’m sorry I won’t make more efforts on compatibility.
