### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by ardikaa** [Perfare/Riru-Il2CppDumper#28]
Hei sir i dont understand what do you mean assemblerelease, can u make me file ready for install in magisk module because i dont know how to use android studio sir
Package name : com.miHoYo.GenshinImpact
UnityVersion : 2017.4.30f1

**Comment by huohuo0470** [comment]
我也在研究genshin 不过我没什么编程基础 啥Android studio也要研究半天，可以在这里讨论鸭。密谋完有结果了到时候删一下帖子好吧·~

**Comment by gyGcYks7Kv** [comment]
我猜测是要把Gen神，Rirudump包一起装到riru+xposed框架里，然后运行某个东西 就有dump出现

**Comment by gyGcYks7Kv** [comment]
其实riru-code本身就是magisk框架里可以下载到的东西，这里的riruIl2Cppdumper是另外一个软体
