### ISSUE TITLE
能不能增加保存内存中的libil2cpp.so和global-metadata.dat及其基地址的功能

### ISSUE THREAD

**Issue by ColdThunder11** [Perfare/Riru-Il2CppDumper#3]
如题，我自己原先想实现一个结果看到了您的这个项目，想问一下是否打算实现。

**Comment by Perfare** [comment]
本项目目前还没完工，在完成TODO列表之前，暂时不考虑新增其他内容。
你可以自己实现，然后考虑发pr给我.
如果你只是单纯的想扣内存，gameguardian就能满足你提到的所有需求。
