### ISSUE TITLE
LOL Wild Rift fails to dump

### ISSUE THREAD

**Issue by sterling0x1** [Perfare/Riru-Il2CppDumper#30]
Hello, this game can't be dumped neither with normal dumper, nor with riru, perhaps they use a new protection.

Unity version from logcat:
11-27 19:24:29.917 26663 26802 I Unity   : Built from '' branch, Version '2018.4.16f1 (0)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'armeabi-v7a'
Logs:
11-27 19:55:37.687   673   673 I Perfare : detect game: com.riotgames.league.wildrift
11-27 19:55:37.721  5073  5093 I Perfare : hack thread: 5093
11-27 19:55:37.722  5073  5093 I Perfare : api level: 28
11-27 19:55:37.729  5073  5093 I Perfare : __loader_dlopen at: 0xe9f722f5
11-27 19:55:52.777  5073  9981 I Perfare : Got il2cpp handle!
11-27 19:55:58.089  5073  5093 I Perfare : il2cpp_handle: 0x36325e95
11-27 19:55:58.091  5073  5093 I Perfare : typeDefinitionsCount: 22614
11-27 19:55:58.093  5073  5093 I Perfare : il2cpp_base: bac6c000
Stops here.

Also normal dumper detects it as 24.1, but fails to dump it.
Logs:

Initializing metadata...
Metadata Version: 24.1
Initializing il2cpp file...
Applying relocations...
WARNING: find .init_proc
ERROR: This file may be protected.
Il2Cpp Version: 24.1
Searching...
CodeRegistration : 0
MetadataRegistration : 0
CodeRegistration : 5fff458
MetadataRegistration : 5fff490
System.ArgumentException: An item with the same key has already been added. Key: 0
  at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x002b6] in <a1336bab325642fd867e87ca7626bada>:0
  at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <a1336bab325642fd867e87ca7626bada>:0
  at Il2CppDumper.Il2Cpp.Init (System.UInt64 codeRegistration, System.UInt64 metadataRegistration) [0x002c4] in <028a4b4e34cb436eb7f3486683fc225f>:0
  at Il2CppDumper.Elf.Search () [0x0021b] in <028a4b4e34cb436eb7f3486683fc225f>:0
  at Il2CppDumper.Program.Init (System.Byte[] il2cppBytes, System.Byte[] metadataBytes, Il2CppDumper.Metadata& metadata, Il2CppDumper.Il2Cpp& il2Cpp) [0x0029b] in <028a4b4e34cb436eb7f3486683fc225f>:0
ERROR: An error occurred while processing.

Playstore link:
https://play.google.com/store/apps/details?id=com.riotgames.league.wildrift

**Comment by RevealedSoulEven** [comment]
Did you used 
#define VersionAbove24

in game.h?

If no then add it

**Comment by Goldtulip** [comment]
> Hello, this game can't be dumped neither with normal dumper, nor with riru, perhaps they use a new protection.
> 
> Unity version from logcat:
> 11-27 19:24:29.917 26663 26802 I Unity : Built from '' branch, Version '2018.4.16f1 (0)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'armeabi-v7a'
> Logs:
> 11-27 19:55:37.687 673 673 I Perfare : detect game: com.riotgames.league.wildrift
> 11-27 19:55:37.721 5073 5093 I Perfare : hack thread: 5093
> 11-27 19:55:37.722 5073 5093 I Perfare : api level: 28
> 11-27 19:55:37.729 5073 5093 I Perfare : __loader_dlopen at: 0xe9f722f5
> 11-27 19:55:52.777 5073 9981 I Perfare : Got il2cpp handle!
> 11-27 19:55:58.089 5073 5093 I Perfare : il2cpp_handle: 0x36325e95
> 11-27 19:55:58.091 5073 5093 I Perfare : typeDefinitionsCount: 22614
> 11-27 19:55:58.093 5073 5093 I Perfare : il2cpp_base: bac6c000
> Stops here.
> 
> Also normal dumper detects it as 24.1, but fails to dump it.
> Logs:
> 
> Initializing metadata...
> Metadata Version: 24.1
> Initializing il2cpp file...
> Applying relocations...
> WARNING: find .init_proc
> ERROR: This file may be protected.
> Il2Cpp Version: 24.1
> Searching...
> CodeRegistration : 0
> MetadataRegistration : 0
> CodeRegistration : 5fff458
> MetadataRegistration : 5fff490
> System.ArgumentException: An item with the same key has already been added. Key: 0
> at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x002b6] in <a1336bab325642fd867e87ca7626bada>:0 at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in :0
> at Il2CppDumper.Il2Cpp.Init (System.UInt64 codeRegistration, System.UInt64 metadataRegistration) [0x002c4] in <028a4b4e34cb436eb7f3486683fc225f>:0
> at Il2CppDumper.Elf.Search () [0x0021b] in <028a4b4e34cb436eb7f3486683fc225f>:0
> at Il2CppDumper.Program.Init (System.Byte[] il2cppBytes, System.Byte[] metadataBytes, Il2CppDumper.Metadata& metadata, Il2CppDumper.Il2Cpp& il2Cpp) [0x0029b] in <028a4b4e34cb436eb7f3486683fc225f>:0
> ERROR: An error occurred while processing.
> 
> Playstore link:
> https://play.google.com/store/apps/details?id=com.riotgames.league.wildrift

The il2cpp structure sames have been reordered.  Try Il2CppInspector.
