### ISSUE TITLE
gradle编译完怎么装到手机里

### ISSUE THREAD

**Issue by gyGcYks7Kv** [Perfare/Riru-Il2CppDumper#31]
我用gradle编译完后，out文件夹中有两个文件夹：magisk_module 文件夹和magisk-riru-il2cppdumper-v1.0.zip压缩包
应该用哪一个，要怎么做 啊啊啊

**Comment by aylz10** [comment]
magisk-riru-il2cppdumper-v1.0.zip导入到手机，然后打开magisk安装模块，选择刚才导入的zip，安装完重启。
ps：riru核心最好使用21.2

**Comment by gyGcYks7Kv** [comment]
啊巴啊巴 rirucore的版本似乎是有点讲究 我一定可以的

**Comment by GodLeaveMe** [comment]
建议将模块更新以兼容Riru-v22.0，需要做的改动非常小，很容易的。

**Comment by aylz10** [comment]
> 建议将模块更新以兼容Riru-v22.0，需要做的改动非常小，很容易的。

你可以创建个Pull requests

**Comment by gyGcYks7Kv** [comment]
全装上了，运行游戏，没找到dump.cs诶，我用的MT管理器，去data-data-com.游戏-files 竟然什么都没有orz

**Comment by gyGcYks7Kv** [comment]
我大致可以弄清楚了，谢谢大家的讨论！关闭话题啦
