### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by MrWildanMD** [Perfare/Riru-Il2CppDumper#34]
Facing error while compilation

Build Log:

`D:\Riru-Il2CppDumper-master\module\src\main\cpp\whale\src\libffi\x86\sysv_i386.S:834:1: error: changed section flags for .eh_frame, expected: 0x2`

**Comment by MrWildanMD** [comment]
fixed by adding multi-line comment to it

**Comment by AWO52PZ44IKE7FDR79DV2999BCZK19R0IFLDGHF** [comment]
> fixed by adding multi-line comment to it

Same issue, can you elaborate on your fix? Thanks much
