### ISSUE TITLE
編譯時出錯

### ISSUE THREAD

**Issue by KCKCC** [Perfare/Riru-Il2CppDumper#35]
D:\downloads\Riru-Il2CppDumper-master\module\src\main\cpp\whale\src\libffi\x86\sysv_i386.S:834:1: error: changed section flags for .eh_frame, expected: 0x2

包名是 "com.square_enix.android_googleplay.SB69Fes"

從level0裡看到的版本是2018.4.14f
所以我版本填 2018.3.8f1

麻煩大神了 感謝

**Comment by GanterPenguin** [comment]
Check out this issue https://github.com/Perfare/Riru-Il2CppDumper/issues/34
