### ISSUE TITLE
without conventional offsets

### ISSUE THREAD

**Issue by FFDATA** [Perfare/Riru-Il2CppDumper#36]
after the dump I realized that the offsets were like this, is this a fault or a protection in the game?

Game: Free Fire 1.58.0

![Clipboard03](https://user-images.githubusercontent.com/77923398/105630271-f6f5bc80-5e26-11eb-8f4f-4169ec670330.jpg)

**Comment by FFDATA** [comment]
other example!

![Clipboard06](https://user-images.githubusercontent.com/77923398/105630465-2c4eda00-5e28-11eb-8a61-8c87d9488c8a.jpg)

**Comment by xzzvsxd** [comment]
YEAH the same！！
