### ISSUE TITLE
已经安装了Riru，为什么提示没用安装。

### ISSUE THREAD

**Issue by a309371807** [Perfare/Riru-Il2CppDumper#39]
- Copying zip to temp directory
- Installing magisk-riru-il2cppdumper-v1.0.zip
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
*********************
 Riru - Il2CppDumper 
*********************
*******************
 Powered by Magisk 
*******************
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: verify.sh
- Extracting verify.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: riru.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: riru.sh.sha256sum
- Verified riru.sh
*********************************************************
! Riru is not installed
! Please install Riru from Magisk Manager or https://github.com/RikkaApps/Riru/releases
*********************************************************
! Installation failed

**Comment by Perfare** [comment]
Riru version has been updated, please download the latest code.
