### ISSUE TITLE
Please add Unity Version

### ISSUE THREAD

**Issue by Matmatew** [Perfare/Riru-Il2CppDumper#4]
please add unity version 2018.4.12f1.

**Comment by sinyo1015** [comment]
You can instead use `2018.3.8f1` version to work with. Because `2018.3.8f1` consist versions of range between `2018.3.8f1 - 2018.4.24f1`.
And also, don't forget to enable `#define VersionAboveV24`.

Tested and working on `Unity 2018.4.18f1` using `2018.3.8f1`

**Comment by Matmatew** [comment]
thank you for your answer, it was very helpful.  I want to try modding GrannyHouse - Multiplayer Horror 
https://play.google.com/store/apps/details?id=net.updategames.granny.  
and it uses the unity version 2018.4.12f1

**Comment by Perfare** [comment]
The project currently supports all versions after 5.3.0f4, please check game.h for a compatible version.
https://github.com/Perfare/Riru-Il2CppDumper/blob/780d0121758e493e3751832ab34bdedbd1c87c0a/module/src/main/cpp/game.h#L34
And don't forget this part
https://github.com/Perfare/Riru-Il2CppDumper/blob/780d0121758e493e3751832ab34bdedbd1c87c0a/module/src/main/cpp/game.h#L11-L12
If you have any questions, feel free to ask questions.
