### ISSUE TITLE
編譯時錯誤

### ISSUE THREAD

**Issue by H3XDaemon** [Perfare/Riru-Il2CppDumper#41]
Riru-Il2CppDumper-master\module\src\main\cpp\il2cpp_dump.cpp:345:27: error: use of undeclared identifier 'il2cpp_image_get_class_count'; did you mean 'il2cpp_image_get_entry_point'?

**Comment by Perfare** [comment]
https://github.com/Perfare/Riru-Il2CppDumper/blob/2d6a2924e11ef09ec4d5c839468e6b764db7bb93/module/src/main/cpp/game.h#L11-L12
Comment it out.
