### ISSUE TITLE
plz have more information on instructions page

### ISSUE THREAD

**Issue by nio04** [Perfare/Riru-Il2CppDumper#43]
![Screenshot_20210302-015859979](https://user-images.githubusercontent.com/58992932/109552870-3bc9de80-7aca-11eb-830c-c2151dcead06.jpg)

![Screenshot_20210302-015040161](https://user-images.githubusercontent.com/58992932/109552683-06bd8c00-7aca-11eb-90ab-213f356b7e66.jpg)

i shared my game unity version & game.h file ... someone plz check & let me know, if everything is correct

**Comment by Perfare** [comment]
using 5.6.0f3
