### ISSUE TITLE
DobbyHook时崩溃

### ISSUE THREAD

**Issue by kudcrafts** [Perfare/Riru-Il2CppDumper#46]
Android version: 11
Magisk version: 22.0
Riru version: 23.9
Game: jp.co.cygames.umamusume
Log:
--------- beginning of main
03-26 16:06:02.464   915   915 I Perfare : detect game: jp.co.cygames.umamusume
03-26 16:06:02.483  1825  2068 I ActivityManager: Start proc 5747:jp.co.cygames.umamusume/u0a365 for broadcast {jp.co.cygames.umamusume/jp.cygames.omotenashi.push.NotificationResetReceiver}
03-26 16:06:02.505  5747  5747 E games.umamusum: Not starting debugger since process cannot load the jdwp agent.
03-26 16:06:02.535  1250  1289 V StorageRedirect: requestCheckProcess: pid=5747, uid=10365, pkg=jp.co.cygames.umamusume
03-26 16:06:02.536  1250  2731 V StorageRedirect: requestCheckProcess: pid=5747, uid=10365, pkg=jp.co.cygames.umamusume
03-26 16:06:02.537  1250  1289 V StorageRedirect: requestCheckProcess: [--enable-file-monitor, --enable-fix-rename]
03-26 16:06:02.537  5747  5747 V StorageRedirectInject: main: package=jp.co.cygames.umamusume, user=0
03-26 16:06:02.544  5747  5747 V StorageRedirectInject: install hook finished
03-26 16:06:02.546  5747  5758 I Perfare : hack thread: 5758
03-26 16:06:02.546  5747  5758 I Perfare : api level: 30
03-26 16:06:02.546  5747  5758 I Perfare : __loader_dlopen at: 0x74236d8190
03-26 16:06:02.546  5747  5758 I Dobby   : [*] [DobbyHook] Initialize at 0x74236d8190
03-26 16:06:02.546  5747  5758 I Dobby   : [*] ================ FunctionInlineReplaceRouting Start ================
03-26 16:06:02.546  5747  5758 I Dobby   : [*] [trampoline] Generate trampoline buffer 0x74236d8190 -> 0x71852144e4
03-26 16:06:02.546  5747  5758 I Dobby   : [*] [insn relocate] origin 0x74236d8190 - 16
03-26 16:06:02.547  5747  5758 I Dobby   : [*] [insn relocate] relocated 0x74222af000 - 56
03-26 16:06:02.547  5747  5758 I Dobby   : [*] [intercept routing] Active patch 0x74236d8190
03-26 16:06:02.547  5747  5758 I Dobby   : [*] ================ FunctionInlineReplaceRouting End ================
03-26 16:06:02.549  5747  5747 W games.umamusum: Core platform API violation: Ljava/lang/reflect/Field;->accessFlags:I from Landroid/os/Build; using reflection
03-26 16:06:02.550   809   815 I Magisk  : proc_monitor: [jp.co.cygames.umamusume] PID=[5747] UID=[10365]
--------- beginning of crash
03-26 16:06:02.583  5747  5747 F libc    : Fatal signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0x74236d819c in tid 5747 (games.umamusume), pid 5747 (games.umamusume)
03-26 16:06:02.820  5770  5770 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-26 16:06:02.821  5770  5770 F DEBUG   : Build fingerprint: 'Xiaomi/raphael/raphael:10/QKQ1.190825.002/V12.0.6.0.QFKCNXM:user/release-keys'
03-26 16:06:02.821  5770  5770 F DEBUG   : Revision: '0'
03-26 16:06:02.821  5770  5770 F DEBUG   : ABI: 'arm64'
03-26 16:06:02.822  5770  5770 F DEBUG   : Timestamp: 2021-03-26 16:06:02+0800
03-26 16:06:02.822  5770  5770 F DEBUG   : pid: 5747, tid: 5747, name: games.umamusume  >>> jp.co.cygames.umamusume <<<
03-26 16:06:02.822  5770  5770 F DEBUG   : uid: 10365
03-26 16:06:02.822  5770  5770 F DEBUG   : signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0x74236d819c (*pc=0x000071)
03-26 16:06:02.822  5770  5770 F DEBUG   :     x0  bb7a3ba2e34b2ea7  x1  0000007fc65cf481  x2  0000000000000000  x3  000000718cc9ecc4
03-26 16:06:02.822  5770  5770 F DEBUG   :     x4  0000000000000010  x5  000000742253797f  x6  395248502d656d75  x7  7a43675f524c552d
03-26 16:06:02.822  5770  5770 F DEBUG   :     x8  000000000000000e  x9  0000000000000000  x10 000000000000000d  x11 0000000000000090
03-26 16:06:02.822  5770  5770 F DEBUG   :     x12 858300000006a107  x13 787a43675f524c55  x14 0000000000000000  x15 0000000079c12ecc
03-26 16:06:02.822  5770  5770 F DEBUG   :     x16 0000007420482140  x17 00000074236d8274  x18 00000074231d4000  x19 0000007fc65cf4a0
03-26 16:06:02.822  5770  5770 F DEBUG   :     x20 0000007fc65cf5d8  x21 000000724cf22e70  x22 0000007422540000  x23 0000000000000000
03-26 16:06:02.822  5770  5770 F DEBUG   :     x24 0000007fc65cf5d8  x25 0000000000000000  x26 0000007fc65cf5c0  x27 000000724cf22e70
03-26 16:06:02.822  5770  5770 F DEBUG   :     x28 0000000000000001  x29 0000007fc65cf450
03-26 16:06:02.822  5770  5770 F DEBUG   :     lr  0000007420481050  sp  0000007fc65cf450  pc  00000074236d819c  pst 0000000040000000
03-26 16:06:03.749  1825  2229 I ActivityManager: Process jp.co.cygames.umamusume (pid 5747) has died: fg  RCVR
03-26 16:06:03.750  1825  2072 I libprocessgroup: Successfully killed process cgroup uid 10365 pid 5747 in 0ms
03-26 16:06:03.752   915   915 I Zygote  : Process 5747 exited due to signal 4 (Illegal instruction)

以我的水平实在搞不懂哪里出问题了，请大佬帮忙看看orz

**Comment by Perfare** [comment]
#50
