### ISSUE TITLE
Port to Xposed module

### ISSUE THREAD

**Issue by ZMODs** [Perfare/Riru-Il2CppDumper#47]
Most newer phones are hard to root and Magisk modules are not working on gaming emulators like LDPlayer and Memu, only crappy AVD are working but most games are not compatible with it.

Please port to Xposed, there would be a huge benefit because we can install Xposed easly on my favorite gaming emulators and on Virtual machines like VMOS and X8 Sandbox for non-root phones. You need to consider that 🙏

**Comment by AndnixSH** [comment]
Yes please, so I don't need to use my crappy phone anymore

**Comment by AndnixSH** [comment]
Finally, non root way which is easier https://platinmods.com/threads/how-to-use-auto-il2cppdumper-to-dump-protected-games-no-root.134194/
