### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by RevealedSoulEven** [Perfare/Riru-Il2CppDumper#5]
Sir actually I am trying to get dump.cs for Garena Free Fire (Android). But I don't know for to use it? 

Can you please make a video tutorial please sir

**Comment by RevealedSoulEven** [comment]
Actually I want to know how to find Unity Version

**Comment by mohdali** [comment]
Easy to google that.

https://answers.unity.com/questions/400473/finding-the-version-of-unity-player-used.html

**Comment by Perfare** [comment]
Edit `game.h` according to the game, and then run gradle task `:module:assembleRelease` task from Android Studio or command line, zip will be saved in `out`.

**Comment by RevealedSoulEven** [comment]
But.... I downloaded the files as zip but I can't find game.h anywhere

**Comment by RevealedSoulEven** [comment]
Ohk I got rhe unity version as 5.6.

But where is game.h folder located in Riru-il2cppdunper?

Maybe I downloaded in the wrong way

Can I please get the link to download it

**Comment by RevealedSoulEven** [comment]
Ohk Sir I got unity version as 5.6.3

So.... According to Riru-il2cppdumper I will write it as 5.6.0f3.
Am I right sir?

**Comment by RevealedSoulEven** [comment]
Sir. Can you please share a magisk flashable zip.file? This one is telling it's not a magisk zip file.

Please send a magisk flashable zip file. I will edit that manually.

Because I tried many ways but.... It says that this is not a magisk module zip file.

**Comment by Perfare** [comment]
Make sure you have [Magisk](https://github.com/topjohnwu/Magisk) and [Riru](https://github.com/RikkaApps/Riru) installed.
Then install this module in Magisk.

**Comment by RevealedSoulEven** [comment]
I have magisk

I have "Riru - Core" module installed in magisk.

What do you mean by Riru? Is it "Riru - Core" right?

I already have edxposed so I definitely have riru.

But can you please share the zip here?

**Comment by mrvizine** [comment]
Would also love an English tutorial as well. But I realize I’m a bit of a newbie too. Any help is appreciated

**Comment by RevealedSoulEven** [comment]
I got anyway 

I already mention on Perfare-Il2cppdumper page

**Comment by ardikaa** [comment]
I don't understand what you mean module: Assemblerelease, where is the file? Please answer me
