### ISSUE TITLE
Error occured while building

### ISSUE THREAD

**Issue by MomokkoW** [Perfare/Riru-Il2CppDumper#51]
![image](https://user-images.githubusercontent.com/78632509/115987831-5364a580-a5e9-11eb-922c-8853df2dcd8e.png)

**Comment by MomokkoW** [comment]
IntelliJ IDEA: 2021.1
Java: 16
Kotlin: 211-1.4.32-release-IJ6693.72
Gradle: 6.6.1

**Comment by H3XDaemon** [comment]
Same

**Comment by Perfare** [comment]
https://github.com/Perfare/Riru-Il2CppDumper/blob/2d6a2924e11ef09ec4d5c839468e6b764db7bb93/module/src/main/cpp/game.h#L11-L12
注释掉
