### ISSUE TITLE
Could not resolve rikka.ndk:riru:10

### ISSUE THREAD

**Issue by Tianbingquan** [Perfare/Riru-Il2CppDumper#53]
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':module:generateJsonModelRelease'.
> Could not resolve all files for configuration ':module:releaseCompileClasspath'.
   > Could not resolve rikka.ndk:riru:10.
     Required by:
         project :module
      > Could not resolve rikka.ndk:riru:10.
         > Could not get resource 'https://dl.bintray.com/rikkaw/Libraries/rikka/ndk/riru/10/riru-10.pom'.
            > Could not GET 'https://dl.bintray.com/rikkaw/Libraries/rikka/ndk/riru/10/riru-10.pom'. Received status code 403 from server: Forbidden

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

**Comment by omegali** [comment]
same problem seems like 'https://dl.bintray.com/rikkaw/Libraries/rikka/ndk/riru/10/riru-10.pom'. cant be accessed?

**Comment by RankoR** [comment]
Bintray was shut down on 1st of May, that's the reason.

**Comment by xhkfd** [comment]
So, riru il2cppdumper not works now?

**Comment by RankoR** [comment]
AFAIR it's hosted on MavenCentral too.

**Comment by xhkfd** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':module:generateJsonModelDebug'.
> Could not resolve all files for configuration ':module:debugCompileClasspath'.
   > Could not resolve rikka.ndk:riru:10.
     Required by:
         project :module
      > No cached version of rikka.ndk:riru:10 available for offline mode.
      > No cached version of rikka.ndk:riru:10 available for offline mode.
      > No cached version of rikka.ndk:riru:10 available for offline mode.
      > No cached version of rikka.ndk:riru:10 available for offline mode.

**Comment by sinyo1015** [comment]
For temporary workaround, try to add the repository to Maven Central. Replace this line 
https://github.com/Perfare/Riru-Il2CppDumper/blob/2d6a2924e11ef09ec4d5c839468e6b764db7bb93/module/build.gradle#L45
into `implementation group: 'dev.rikka.ndk', name: 'riru', version: '10'`
and also this line 
https://github.com/Perfare/Riru-Il2CppDumper/blob/2d6a2924e11ef09ec4d5c839468e6b764db7bb93/module/build.gradle#L33
https://github.com/Perfare/Riru-Il2CppDumper/blob/2d6a2924e11ef09ec4d5c839468e6b764db7bb93/build.gradle#L22
into `mavenCentral()`

**Comment by Perfare** [comment]
I have upgraded the riru version to 26, it should have been fixed.
