### ISSUE TITLE
rikka.ndk:riru:10

### ISSUE THREAD

**Issue by xhkfd** [Perfare/Riru-Il2CppDumper#55]
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':module:generateJsonModelDebug'.
> Could not resolve all files for configuration ':module:debugCompileClasspath'.
   > Could not resolve rikka.ndk:riru:10.
     Required by:
         project :module
      > No cached version of rikka.ndk:riru:10 available for offline mode.
      > No cached version of rikka.ndk:riru:10 available for offline mode.
      > No cached version of rikka.ndk:riru:10 available for offline mode.
      > No cached version of rikka.ndk:riru:10 available for offline mode.

**Comment by Perfare** [comment]
I have upgraded the riru version to 26, it should have been fixed.
