### ISSUE TITLE
how to enable #define VersionAboveV24? game is crashing.

### ISSUE THREAD

**Issue by omegali** [Perfare/Riru-Il2CppDumper#56]
#define GamePackageName "com.arcsystemworks.bbdw"
#define UnityVersion 2019.3.7f1

// 2018.3.0f2(v24.1) and up enable it
#define VersionAboveV24

my game.h

i looked at the similar issues and perfare said to enable #define VersionAboveV24 but i dont know what to change with it.

the game version is 2019.4.14f1

**Comment by H3XDaemon** [comment]
Maybe version above 2019.4.4f1 is not supported yet

**Comment by H3XDaemon** [comment]
Your define is correct

**Comment by NettixCode** [comment]
same problem here... unityversion 2018.4.31f1 .. how to solved this ??
is it change to compability version with #define VersionAboveV24 enable or how ?

**Comment by stelauAR** [comment]
> same problem here... unityversion 2018.4.31f1 .. how to solved this ??
> is it change to compability version with #define VersionAboveV24 enable or how ?

#define UnityVersion 2018.4.31f1
