### ISSUE TITLE
模擬器如何使用riru-il2cpp dumper?

### ISSUE THREAD

**Issue by benson591** [Perfare/Riru-Il2CppDumper#57]

**Comment by AndnixSH** [comment]
Use Auto-Il2cppdumper https://platinmods.com/threads/how-to-use-auto-il2cppdumper-to-dump-protected-games-no-root.134194/

**Comment by benson591** [comment]
Thanks a lot :) !!

    在 2021年7月6日 星期二 下午9:45:00 [GMT+8]， ***@***.***> 寫道：  
 
 


Use Auto-Il2cppdumper https://platinmods.com/threads/how-to-use-auto-il2cppdumper-to-dump-protected-games-no-root.134194/
