### ISSUE TITLE
cmake_module_path error

### ISSUE THREAD

**Issue by RevealedSoulEven** [Perfare/Riru-Il2CppDumper#62]
I just download and installed everything and even without changing anything in the files it gave this error.

Can you please help?
![IMG_20210804_194119](https://user-images.githubusercontent.com/49313374/128201332-26e7f706-51db-4256-8c86-bb8227486969.jpg)
![Uploading IMG_20210804_194119.jpg…]()

**Comment by RevealedSoulEven** [comment]
![Uploading IMG_20210804_194119.jpg…]()

**Comment by JMBQ** [comment]
Please configure your android studio

**Comment by RevealedSoulEven** [comment]
What do you mean??

**Comment by RevealedSoulEven** [comment]
how to configure please tell

**Comment by RevealedSoulEven** [comment]
can you please tell me the proxy settings? this error is due to forbidden dl.bintray.com @JMBQ

**Comment by JMBQ** [comment]
说中文？

**Comment by Perfare** [comment]
I have upgraded the riru version to 26, it should have been fixed.
