### ISSUE TITLE
Riru dumper not giving Dump.cs for freee firee 

### ISSUE THREAD

**Issue by Critical-Mods** [Perfare/Riru-Il2CppDumper#64]
So my problem is  I had installed Riru and riru il2cpp dumper correctly without any of the errors but when I start the game and after wait for a while and check in the files there is no dump.cs why I don't know what's the problem need help ASAP PLZ🙏 
![IMG-20210818-WA0000](https://user-images.githubusercontent.com/80670128/129899087-dfb2b3a1-b4e2-4815-9e5c-ca4c68eaa8d1.jpeg)

**Comment by BryanGIG** [comment]
Its on the directory root your game

**Comment by Critical-Mods** [comment]
It's not there also bro

**Comment by Perfare** [comment]
Your Il2CppDumper version is too low, it has not been loaded by Riru.
