### ISSUE TITLE
help offset address

### ISSUE THREAD

**Issue by Lexs194** [Perfare/Riru-Il2CppDumper#7]
i got this file dump.cs but i don't understand this RVA address because can't match with offset libil2cpp.so file. is this encrypted address?
![image](https://user-images.githubusercontent.com/26144961/89100886-864c8500-d42d-11ea-9eb5-51117b18cfd5.png)

**Comment by Perfare** [comment]
It looks like the module base address failed to get, give me the game name and I will check it.

**Comment by Lexs194** [comment]
Game name: Exos Heroes

**Comment by Perfare** [comment]
Fixed.

**Comment by Lexs194** [comment]
don't know why today can not run the game just black screen after install new module.
my step:
delete existing module - reboot
install new module - reboot - run the game - black screen

**Comment by Perfare** [comment]
I don’t know why it happened, maybe you just need to restart the game.

**Comment by Lexs194** [comment]
i close this issue, maybe my phone can not handle it.. old phone btw :D 
thank for you help @Perfare
