### ISSUE TITLE
UnityVersion 2020.2.4f1 - Error il2cpp_dump.cpp:422:39: error: no member named 'vector' in 'Il2CppArray'

### ISSUE THREAD

**Issue by david8557** [Perfare/Riru-Il2CppDumper#71]
If we use #define UnityVersion 2020.2.4f1 and #define VersionAbove2020dot2, it will have error at this line
auto items = reflectionTypes->vector;

**Comment by Perfare** [comment]
Why would you comment out '#define VersionAbove2018dot3'
