### ISSUE TITLE
Android - Unity 2020.3.16f1

### ISSUE THREAD

**Issue by iAlexAR** [Perfare/Riru-Il2CppDumper#73]
Hi, from the looks of it unity has this version 2020.3.16f1 which is currently not supported. Even if using the dumper with the closest version 2020.2.4f1 does not work or even when using 2021.1.0f1. It will produce an inconsistent dump.cs file with only the Assemblies names. 

Example game https://play.google.com/store/apps/details?id=jp.co.gu3.alchemist

**Comment by Perfare** [comment]
same #76
