### ISSUE TITLE
0 bytes dump.cs

### ISSUE THREAD

**Issue by KarmaMod** [Perfare/Riru-Il2CppDumper#75]
I try to dump Standoff 2 but it comes out 0 bytes dump.cs. Dump works ok on other protected games

![Screenshot_20210920-192800-507](https://user-images.githubusercontent.com/88159598/134047199-c15ce7cb-3180-42a0-8c94-be663c791010.png)

![Screenshot_20210920-192714-100](https://user-images.githubusercontent.com/88159598/134047183-3ff12ae6-2b44-42f2-98c8-aee019b2b3b7.png)

**Comment by Perfare** [comment]
![image](https://user-images.githubusercontent.com/12952226/142716995-139e21dc-14b7-4414-bbba-00fb19f42448.png)
The game did something to anti dump.
