### ISSUE TITLE
Wrong offsets

### ISSUE THREAD

**Issue by KarmaMod** [Perfare/Riru-Il2CppDumper#79]
Thanks for fixing crash for Dq dai. however the offsets are incorrect. Can you solve it?
[com.square_enix.android_googleplay.dqdaihb-dump.zip](https://github.com/Perfare/Riru-Il2CppDumper/files/7608873/com.square_enix.android_googleplay.dqdaihb-dump.zip)

**Comment by Perfare** [comment]
need log.

**Comment by KarmaMod** [comment]
nevermind, it's the issue on emulator, offsets are correct when dumped on phone
