### ISSUE TITLE
如何获得特定版本的api-functions文件和class.h文件

### ISSUE THREAD

**Issue by Colibrow** [Perfare/Riru-Il2CppDumper#81]
你好，比如我这边想获取到2017.4.30f1版本的头文件，我下载后在目录只能找到il2cpp-api-functions.h找不到另一个
![image](https://user-images.githubusercontent.com/11855760/150333924-7734d42c-c51f-4889-a647-37f240317845.png)

**Comment by Perfare** [comment]
结构体存在于其他多个.h文件中
https://github.com/nneonneo/Il2CppVersions
